### PR TITLE
Modified order of components to fix CSS border styling

### PR DESCRIPTION
**Pull request by luketherrien**
This pull request fixes a CSS styling issue by reorganizing the components contained in the render method. Specifically, I moved the FormControl to be the first component.

After merging this pull request, the input element should have rounded corners on the left side (since it's the first child of an input group).

### CODE REVIEW

**Comment by luketherrien** [comment]
Any idea if this is going to get accepted?

**Comment by wehriam** [comment]
Many thanks for the PR and apologies for the delay in it's review and acceptance. I'll take a look as soon as possible.

**Comment by luketherrien** [comment]
No problem at all! Sorry for being pushy. Thanks so much for the awesome plugin!

**Comment by keropodium** [comment]
It seems that #52 broke this. Could you double check?

**Pull request merged**
