### PR TITLE
Added some extra options

### PR DESCRIPTION
**Pull request by hoest**
Added:

  * `showTodayButton` - Toggles the visibility of the today-button.
    * **Optional**
    * **Type:** `boolean`
    * **Example:** `false`
  * `todayButtonLabel` - Label for the today-button
    * **Optional**
    * **Type:** `string`
    * **Example:** `"Today"`
  * `customControl` - Overwrite the default `FormControl` component with your own component.
    * **Optional**
    * **Type:** `React.Component`
    * **Example:** `<CustomControl />`

### CODE REVIEW

**Comment by wehriam** [comment]
@hoest this is fantastic, thank you for the PR. This is a community developed project and only possible because of contributions like this.

Before I merge:

* Please implement tests for each item.
* Add a 'lint' script to`package.json`

**Comment by hoest** [comment]
I've added `npm run test` and some tests.

**Comment by wehriam** [comment]
Can you resolve the merge conflicts?

**Comment by hoest** [comment]
I will resolve these conflict, but currently your tests are failing. Could you please fix that?

**Comment by wehriam** [comment]
The tests are passing on master as of the latest commit - https://circleci.com/gh/pushtell/react-bootstrap-date-picker

**Comment by hoest** [comment]
When I run them locally, I get this (on the updated `master` branch):

image

```
Date Picker should render a date picker with a value. FAILED
	'20/11/2016' == '11/20/2016'
	callee$1$1$@webpack:///test/core.test.jsx:96:21 <- tests.bundle.js:213:36
	tryCatch@webpack:///~/regenerator-runtime/runtime.js:63:14 <- tests.bundle.js:48692:45
	invoke@webpack:///~/regenerator-runtime/runtime.js:337:0 <- tests.bundle.js:48966:31
	onFulfilled@webpack:///~/co/index.js:65:0 <- tests.bundle.js:42970:24
	promiseReactionJob@[native code]
```

**Comment by hoest** [comment]
@wehriam: I resolved the conflicts.

**Pull request merged**
