### PR TITLE
Add test case and implementation for #45

### PR DESCRIPTION
**Pull request by discordier**
This introduces a new property named "valueFormat".
This property allows to have an alternative value format aside from
"iso" date format.

### CODE REVIEW

**Comment by discordier** [comment]
@wehriam any news on this one?

**Comment by wehriam** [comment]
Hi @discordier - I sincerely appreciate the PR. This module would not be possible without the support of the community.

It seems like there are two issues in https://github.com/pushtell/react-bootstrap-date-picker/issues/45

1. "...if the hour is 23 and the date is 31th of October, we get timezone issues..."
2. Getting a formatted date out of the system.

Your solution will not resolve 1) because the component uses ISO date strings internally.

Regarding 2) I'm not sure setting a property is a good way to implement this functionality. It makes the JSX more difficult to read, and developers would need to remember to set the property each time.

What if we instead added a `getFormattedValue()` method, and added the formatted value as a second parameter to the `onChange()` callback?

```js
<DatePicker ref="datePicker" value={this.state.value} onChange={(isoStringValue, formattedValue) => {console.log(formattedValue)}} />
```

```js
const formattedValue = this.refs.datePicker.getFormattedValue();
console.log(formattedValue); // Example "12/15/2016"
```

**Comment by wehriam** [comment]
Regarding 1) we might want to make sure that any internal date object is set to 12:00pm local time to avoid timezone issues.

**Comment by discordier** [comment]
I am happy with the solution to force every timestamp to 12:00pm, I do not see any issues with that.

for your suggestion about the `getFormattedValue` method, how do you intend to inject the format string?
A little more verbose (real application) code would be helpful here.
Using my method, you could write:
```jsx
<DatePicker valueFormat="YYYY-MM-DD" dateFormat="YYYY-MM-DD" value={this.state.value} />
<DatePicker valueFormat="We have now the DD of MM in the year of YYYY" dateFormat="YYYY-MM-DD" value={this.state.value} />
```
How do I inject the format using:
```jsx
<DatePicker 
  ref="datePicker" 
  value={this.state.value} 
  onChange={(isoStringValue, formattedValue) => {
   /* how is formattedValue built here? From what format string? */
    console.log(formattedValue)
  }} />
```

We might also decide to implicitly switch the `valueFormat` to inherit the `displayFormat` defined and therefore have both values at hand.
However, I decided against doing so because of backwards compatibility concerns as currently an iso date string is returned and it would change that behaviour.

**Comment by wehriam** [comment]
Resolved in `3.8.0` via a the addition of `formattedValue` to the `onChange()` handler. See updated documentation.

**Pull request closed without merging**
