### PR TITLE
Support for custom separator

### PR DESCRIPTION
**Pull request by Reggino**
Hi!

Awesome stuff... Thanks for this!

The following changes allow the date-separator to be changed to whatever you like. As seen here https://en.wikipedia.org/wiki/Date_format_by_country there a few possible characters that could be used to separate the different parts of the date-string. With these changes, the date-separator character is read from the `dateFormat`-config and applied as needed.

### CODE REVIEW

**Comment by Reggino** [comment]
To use this myself, i had to integrate PR #9. I reformatted it, but all credits go to @SubatomicHero

**Comment by Reggino** [comment]
( test should no longer fail )

**Comment by wehriam** [comment]
This is fantastic, thanks @Reggino! I'll review in the next few hours then release.

**Comment by wehriam** [comment]
And of course thanks @SubatomicHero!

**Comment by wehriam** [comment]
Quick update - the dependency updates associated with this PR are causing problems in Firefox. Should have a solution soon.

**Comment by brian-kellerheikkila** [comment]
Any update on this? Thanks.

**Comment by wehriam** [comment]
This has been implemented in the `3.0.0` release. You can find more information in the [documentation](https://github.com/pushtell/react-bootstrap-date-picker#datepicker-) or see it in action in the "date format" section of the [demo](http://pushtell.github.io/react-bootstrap-date-picker/).

**Pull request merged**
