### PR TITLE
Update to bootstrap and fix console errors

### PR DESCRIPTION
**Pull request by SubatomicHero**
- Update package json to update bootstrap.
- Used InputGroups/FormGroups to structure the element.

### CODE REVIEW

**Comment by wehriam** [comment]
Huge thanks for the PR. 

Can you change the files to two spaces? I'm having a hard time evaluating the diff.

**Comment by SubatomicHero** [comment]
Sure will do. I might not get around to it for a few days though :)

**Comment by brian-kellerheikkila** [comment]
When will this be pushed to npm? When I try to install it, I get this error:
npm ERR! peerinvalid Peer react-bootstrap-date-picker@2.0.0 wants react-bootstrap@^0.28.1

**Comment by wehriam** [comment]
This PR had an issue in Firefox, so unfortunately it's not ready yet. Working on it though and will try to get it out today.

**Pull request closed without merging**
