### PR TITLE
Restricted dates & rounded corners options - Issue #18 & #40

### PR DESCRIPTION
**Pull request by Rikku-1**

### CODE REVIEW

**Comment by wehriam** [comment]
@Rikku-1 this is great, many thanks for the PR. The date picker is a community developed project and only possible because of contributions like this.

Before I merge:

* Please implement tests for each item.

**Comment by wehriam** [comment]
Also, can you resolve the merge conflicts?

**Comment by wehriam** [comment]
@Rikku-1 hope you'll have a chance to look at this soon!

**Comment by Rikku-1** [comment]
Sorry, I had a busy holiday.  I'm working on this again now.

**Comment by wehriam** [comment]
@Rikku-1 no rush on my end! We appreciate your contribution.

**Comment by jorgecuesta** [comment]
@Rikku-1 @wehriam some news about merge @Rikku-1 mix/max dates range?

**Comment by jorgecuesta** [comment]
@wehriam @Rikku-1  some new about merge min max date ranges? Please!

**Pull request closed without merging**
