### PR TITLE
Fixed order of control in input group

### PR DESCRIPTION
**Pull request by Robinfr**
See issue: https://github.com/pushtell/react-bootstrap-date-picker/issues/68

### CODE REVIEW

**Comment by LorneCurrieHomes** [comment]
how do we get this PR merged? This affect my code base as well.

**Comment by Robinfr** [comment]
I'm not sure the author is still working on this library since I created the issue a month ago..

Op 8 feb. 2017 8:59 p.m. schreef Lorne Currie <notifications@github.com>:

how do we get this PR merged? This affect my code base as well.

**Comment by wehriam** [comment]
Can you confirm this is still necessary after https://github.com/pushtell/react-bootstrap-date-picker/pull/66 ?

Thank you for the PR.

**Comment by Robinfr** [comment]
@wehriam I don't think so. It fixes the same problem. :smile:

**Pull request closed without merging**
