### PR TITLE
Set first day of the week

### PR DESCRIPTION
**Pull request by hoest**
`weekStartsOn` - Makes the calendar's week to start on a specified day. 0 = Sunday, 1 = Monday, etc.

* **Optional**
* **Type:** `number`
* **Example:** `4`

### CODE REVIEW

**Comment by hoest** [comment]
@wehriam have you got any idea when (or if) this PR will be merged?

**Comment by wehriam** [comment]
Wouldn't this conflict with the "weekStartsOnMonday" property?

**Comment by hoest** [comment]
Both options, `weekStartsOnMonday` and `weekStartsOn`, will work.

**Comment by wehriam** [comment]
Ok, thanks for the PR. Can you resolve the conflicts, remove the `weekStartsOnMonday` property, and make sure we have test coverage for the new functionality?

**Comment by hoest** [comment]
I've resolved the conflicts and made `weekStartsOnMonday` obsolete. @wehriam It's ready to merge!

**Comment by wehriam** [comment]
Awesome, thanks!

**Pull request merged**
