### PR TITLE
Restricted dates & rounded corners options - Issue #18 & #40

### PR DESCRIPTION
**Pull request by Rikku-1**

### CODE REVIEW

**Comment by Rikku-1** [comment]
I realized it made more sense to create a new pull request set against the forked master branch.  Let me know if there's anything else I can do.

**Comment by Vincz** [comment]
Hello guyz !
Any update about this PR ?

**Comment by nevace** [comment]
I was implementing the minmax date thing myself but nice to see this PR. Please merge :)

**Comment by codrobin33** [comment]
:+1:

**Pull request merged**
