### PR TITLE
Replaced React.PropTypes reference with PropTypes

### PR DESCRIPTION
**Pull request by JonShort**
## Description
Replaced one area which was referencing `React.PropTypes` to use `PropTypes` from the `prop-types` library.

## Motivation and Context
Should fix PropTypes warnings which this library causes in itself, and other projects.

## How Has This Been Tested?
Test suite ran, PropTypes warning no longer appears in tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by capaj** [comment]
why is this not merged yet?

**Comment by JonShort** [comment]
@wehriam Any chance this could be merged?

**Comment by aanguswilliams** [comment]
What is going on with this library, multiple PRs for bugs in master that haven't been merged

**Comment by wehriam** [comment]
@capaj and @aanguswilliams this is a community supported project. We do our best to address PRs and issues, but unfortunately have other professional obligations that preempt this work.

If you're interested in custom features or professional support for this project, please feel free to reach out to me directly. 

I've added @JonShort as a contributor and  humbly request he evaluate/merge this and other PRs as soon as he has a chance.

**Comment by aanguswilliams** [comment]
Apologies, I do 100% appreciate the contributions yourself and others have made to the open source community and understand there's no obligation to keep it up to date. Just wasn't sure what was going on with the timelines and was hoping to determine whether contributions were even still being taken. Thanks for your work.

**Comment by capaj** [comment]
@wehriam no problem, I was merely asking. I know activity in the PR thread increase the chance the PR will get the attentions from maintainers. Awesome that you've made @JonShort a contributor.

**Pull request merged**
