### PR TITLE
Min/Max Improvements

### PR DESCRIPTION
**Pull request by docrinehart**
Fixes Issue #96

### CODE REVIEW

**Comment by parthshah1991** [comment]
Is this going to be merged any time soon?

**Comment by wehriam** [comment]
Hi @parthshah1991 this is a community supported project. We do our best to evaluate and promptly integrate pull requests.

If you have a commercial priority associated with this project you can fork the repository or contact me directly to discuss your immediate goals.

**Comment by NullVoxPopuli** [comment]
I'd also like min/max functionality!

**Comment by docrinehart** [comment]
@NullVoxPopuli To clarify, this IMPROVES min/max functionality. If you are using the latest version (5.0.1) from npm, there is a basic implementation that disables dates outside the min/max range.

**Comment by NullVoxPopuli** [comment]
oh? I just didn't see anything about min/max here: https://github.com/pushtell/react-bootstrap-date-picker#api-reference

**Comment by docrinehart** [comment]
Indeed, the API reference was not updated when the basic min/max props were originally added, but I have updated the documentation in this PR as well as added a configurable min/max sample to the demo app.

**Comment by wehriam** [comment]
Waiting on BrowserStack to re-upgrade the open source account.

**Pull request merged**
