### PR TITLE
Added calendarContainer property

### LINKED ISSUE #33: The calendar popover is clipped when placed in a scrollable container
When I place the react-bootstrap-date-picker in a scrollable container and I click in the input field, the calendar pops up but it is clipped to the container boundary. If I put up a raw react-bootstrap popover next to it, this popover correctly shows in full, sitting on top of the scrollable container. How can I make the react-bootstrap-date-picker behave the same way?

image

Here's my code:

```
    render() {
        return (
            <div className={ style['bulk-processing'] + ' panel panel-primary' } >
                <div className="panel-heading">Scrollable Panel</div>
                <div className="panel-body scrollable">
                    <Popover
                        id="popover-basic"
                        placement="right"
                        positionLeft={325}
                        positionTop={50}
                        title="Popover right"
                    >
                        And here's some <strong>amazing</strong> content. It's very engaging. right?
                    </Popover>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/>
                    Hello World<br/><br/>

                    <div className="container-fluid">
                        <div className="col-xs-4">
                            <DatePicker
                                id="start-date"
                                dateFormat="MM/DD/YYYY"
                            />
                        </div>
                    </div>
                </div>
            </div>
        );
    }
```

The `scrollable` class is defined as follows:

```
.scrollable {
    -ms-overflow-style: scrollbar;
    overflow: auto;
}

```

### PR DESCRIPTION
**Pull request by nareshbhatia**
This property allows the popover calendar to work correctly when the date-picker is placed inside a scrolling container. Fixes #33.

### CODE REVIEW

**Comment by nareshbhatia** [comment]
@wehriam, I am sure you are very busy, but any chance of reviewing/accepting this PR? It is in our critical path.

Thanks in advance for your time.

**Comment by wehriam** [comment]
Thanks for the PR. I'll try to review today.

**Comment by wehriam** [comment]
@nareshbhatia - To accelerate the release please update the example application and write test cases to cover this new code.

**Comment by nareshbhatia** [comment]
@wehriam - will do.

**Comment by nareshbhatia** [comment]
@wehriam, I have added a test and updated the example. Looks pretty solid to me now. Please review.

**Comment by wehriam** [comment]
Release 3.6 to NPM. Thanks for the PR!

**Comment by nareshbhatia** [comment]
Thanks for a quick response! This allows me to release my app to prod tonight.

**Pull request merged**
